apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: demo-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 1
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 1
            periodSeconds: 2