apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: demo-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8090